### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by roaldarbol** [conda-forge/rstudio-feedstock#29]
### Comment:

The current version is ~1 year behind, so it would be great to have it updated. Looking at the pipeline checks, most of them fail, and it seems to be due to [BUILD NOT FOUND](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=846463) on Azure. Not having looked a these pipelines, I'm not sure what that means though...

**Comment by h-vetinari** [comment]
The builds started failing for an undetermined reason, and azure pipelines will delete the CI logs for a PR after a month. You can try to restart any of the PRs (or open one yourself) and try to fix it. I can review and try to help out

**Comment by chrishaak** [comment]
Just seconding this update request - thank you!

**Comment by mfansler** [comment]
FYI, I restarted the CI on [the latest autotick-bot PR](https://github.com/conda-forge/rstudio-feedstock/pull/28) so you can examine the logs. Apparently [the patches need updating](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=868159&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=ecca2736-6363-55be-133f-faae951bb9b5&l=1068).

**Comment by h-vetinari** [comment]
I did rebase the patches in https://github.com/conda-forge/rstudio-feedstock/pull/20, and it still failed.

**Comment by chrishaak** [comment]
Just following up on potential for an update of this?  I'm sorry to say it's beyond my skillset or I'd attempt to help...

**Comment by h-vetinari** [comment]
Just give it a try, and when you hit an error, research it, and leave some notes in the PR for yourself or anyone else that may follow. That's the only realistic way to solve such situations.

I'm taking care of 100s of packages and am not interested enough in rstudio to smash my head against this particular wall (though I'll try to provide feedback on whatever it is you're stuck on). That's exactly how I learned initially - just try and don't give up easily.

**Comment by chrishaak** [comment]
Ok I'll give it a shot; is there a "how-to/for dummies" guide for this
somewhere that I can refer to?

**Comment by h-vetinari** [comment]
Best way to start is probably to have a look through the [knowledge base ](https://conda-forge.org/docs/maintainer/knowledge_base/), or look at some merged PRs (and their discussions) in https://github.com/conda-forge/staged-recipes (which is where feedstocks start out from).

Other than that, open a PR and work your way through whatever issues pop up in CI. It helps to be at ease with git, because there's currently patches applied to the rstudio sources here, and as the sources change, the patches might need adapting as well. You can have a look what I did in #20, or base your work on top of that PR from the get go.

**Comment by h-vetinari** [comment]
So we made a jump forward with #32. Hopefully the next versions are going to be easier.

**Comment by roaldarbol** [comment]
Brilliant work, thanks!
